services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=todos_db
      - MYSQL_ROOT_PASSWORD=123456789
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/init.sql

  todo-api:
    image: todo-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./TodoApi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db

  client:
    image: client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - todo-api
volumes:
  db:
    driver: local