version: '2'

services:
    mysqlserver:
        image: database
        restart: always
        build:
            context: ./Database
            dockerfile: Dockerfile
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - mynetwork
    server: 
        image: server:latest
        ports:
            - 8888:80
        build:
            context: ./Server
            dockerfile: Dockerfile
        links:
            - mysqlserver
        depends_on:
            - mysqlserver
        networks:
            - mynetwork
    client:
        image: client
        ports:
            - 8080:8080
        build:
            context: ./ClientVue
            dockerfile: Dockerfile
        links:
            - server
        depends_on:
            - server
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge