version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: MyStrongPassword123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    depends_on:
      - db
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

volumes:
  dbdata:
