version: '3'

services:
  frontend:
    build: ./front-end
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mynetwork

  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_USER=tranlam
      - MYSQL_PASSWORD=Calendar20
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
