# Base image
# FROM node:lts-alpine as build

# Working directory
# WORKDIR /app


# COPY package.json /app/package.json
# RUN npm install

# COPY . /app/dist

# RUN npm run build

FROM nginx:alpine

# COPY --from=build /app/dist /usr/share/nginx/html


COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY dist/BugTracking/. /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]